-- Enable the pgvector extension for AI search
CREATE EXTENSION IF NOT EXISTS vector;

-- Create Authors table
CREATE TABLE IF NOT EXISTS authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Remedies table
CREATE TABLE IF NOT EXISTS remedies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT REFERENCES authors(id),
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    full_text TEXT NOT NULL,
    url TEXT,
    embedding VECTOR(384),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(author_id, slug)
);

-- Create the AI Search Function
CREATE OR REPLACE FUNCTION match_remedies (
  query_embedding VECTOR(384),
  match_threshold FLOAT,
  match_count INT
)
RETURNS TABLE (
  id BIGINT,
  name TEXT,
  author_name TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    r.id,
    r.name,
    a.name as author_name,
    1 - (r.embedding <=> query_embedding) AS similarity
  FROM remedies r
  JOIN authors a ON r.author_id = a.id
  WHERE 1 - (r.embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
END;
$$;
